### ISSUE TITLE
pin tbb

### ISSUE THREAD

**Issue by looooo** [conda-forge/conda-forge-pinning-feedstock#123]
recently we see problems arising from updating an environment as an incompatible version of tbb is pulled in. I guess tbb should be pinned to avoid this problems.

**Comment by looooo** [comment]
close this for now as I am not sure if this is reproduceable...

**Comment by looooo** [comment]
reopen as it seems that the newest tbb is not binary compatible with older versions. So we have to pin it in some way.

**Comment by mariusvniekerk** [comment]
This one?  https://abi-laboratory.pro/?view=timeline&l=tbb

**Comment by looooo** [comment]
yes, thi one here:
https://github.com/conda-forge/tbb-feedstock

**Comment by anton-malakhov** [comment]
@looooo It's not about binary compatibility. It's about platform support matrix on the source level. e.g. VS2008 and OSX 10.9 are not officially supported anymore, though per our request it is supported unofficially :) The binary compatibility of libtbb itself is not affected because the symbols which were introduced in old version of the library are still there.

**Comment by looooo** [comment]
But if newer tbb-version won't work for conda-packages on osx, I think it would be nice if tbb would be pinned (This way not all packages have to specify the pinning manually.)

**Comment by looooo** [comment]
I would pin 2019.2 once it is available. This pinning can be removed once the osx version of the ci has been updated.

**Comment by isuruf** [comment]
Why is it that a new version is incompatible with older ones? From the ABI compatibility report, it seems like it should be.

**Comment by anton-malakhov** [comment]
It is not, I guess Lorenz mixes build and runtime compatibility. I bet when users upgrade their tbb in the environment with current freecad to tbb 2019.1, there will be no issues with that. It will just work - this is binary backward compatibility. So, please **don't pin `tbb` package** anyhow.

What likely happened is that new Xcode (is it new?) with compatibility target set to old 10.9, changed the way the exception class is defined, so it did not connect to the way how TBB headers discover it. So, this is strictly compile-time issue with `tbb-devel 2019.1` package, which does not affect backward compatibility of any `tbb` package. Pinning `tbb-devel` to an older version is ok or even encouraged because it enables flexibility to use older runtimes. Though doing it globally doesn't make much sense to me since applications define, which minimal version they want to use. Of course, since we restructured the `tbb` package into multiple packages in 2018.0.4 and it was broken in Anaconda's default channel on linux, the oldest version one can reasonably use is `tbb-devel 2018.0.5`

**Comment by looooo** [comment]
thanks for the clarification. I see now that pinning tbb doesn't make much sense (as it should be backward-compatible).
I will set tbb-devel-version to 2018.0.4 for my failing build and update this once the next tbb-devel is available.

**Comment by anton-malakhov** [comment]
the reason it makes sense to set it to 2018.0.5 is that packages from default channel can easily sneak into user's environment, while 2018.0.4 package on default was broken on linux (unless it was re-built there) as explained here: https://github.com/numba/numba/pull/3202#issuecomment-415939206

**Comment by looooo** [comment]
I guess this can be closed now (no problems with current tbb versions)
