### ISSUE TITLE
OpenSSL 3.0 migration

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#1894]
I haven't ever started a migration, but after https://github.com/conda-forge/openssl-feedstock/pull/72, it's gonna be necessary.

Also note that the pinning _level_  will need to change because OpenSSL adopted SemVer (effectively), see https://www.openssl.org/policies/releasestrat.html

CC @conda-forge/openssl

**Comment by jmarshall** [comment]
I notice that even with #1896 having been merged, _recipe/conda_build_config.yaml_ still contains

```
openssl:
  - 1.1.1
```

Is this intended? What is the status of migration to OpenSSL 3.0? Is there something further needed here to complete the migration?

**Comment by chrisburr** [comment]
The migration is ongoing and you can see the file in `recipe/migrations/openssl3.yaml`.

If you look at https://conda-forge.org/status/ you can see the status by clicking on "Other Migrations" and searching for "openssl". I suspect it'll take a while before everything gets rebuilt, please feel free to help out with fixing failing PRs if you're able! 🙂

**Comment by jmarshall** [comment]
Thanks for the information.

I am unaware of the wider goals of the migration. Is there documentation of how files like _openssl3.yaml_ are used? Looking at one of the PRs linked from that status page, it appears that the intention is to carry on building packages for both flavours of openssl — is that true? Or perhaps only until migration is complete, at which time the older files like _.ci_support/linux_64_openssl1.1.1.yaml_ will be dropped?

My interest is in building bioconda packages (cf bioconda/bioconda-recipes#30786), which currently are being built only against 1.1.1l due to that line in _recipe/conda_build_config.yaml_. If the intention is to update that pinning line (to `- 3` I guess) when the migration of conda-forge packages is complete, that would be of interest and would describe how bioconda will be affected by this ongoing work.
