### ISSUE TITLE
2 conflicting `poppler` migrations (`23.01` & `23.03`)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#4270]
Currently there are 2 `poppler` migrations running that are trying to update to different `poppler` versions. Should we close one of these out (presumably the older one)?

cc @conda-forge/core @conda-forge/poppler

**Comment by jakirkham** [comment]
Also somewhat curious how we wound up with 2 of these (as opposed to closing the old one out)

**Comment by xylar** [comment]
@jakirkham, is this giving you trouble?  It's not at all unusual to have multiple migrations for a package going on at the same time.  See, for example, `libnetcdf`.

https://conda-forge.org/status/#libnetcdf491
https://conda-forge.org/status/#libnetcdf492

It can take awhile for the migration to propagate and it's not at all clear to me that it's a good idea to close one migration just because another has started.  It's somewhat inevitable that new versions of packages, as they come out, will only have the latest of these migrations and that that can cause some difficulties (that's happening with `libnetcdf` and `hdf5` in a few places for me right now) but my hunch is that this would be made worse, not better, if we stopped the earlier migration.

I can't speak to the `poppler` migration itself since I don't use enough downstream packages to see the trouble.  Again, are there specific problems that woudl be solved by closing the `23.01` migration?

**Comment by jakirkham** [comment]
Would have thought that we would consolidate these into a single migration with a matrix if we wanted multiple versions of a dependency supported

**Comment by jakirkham** [comment]
Alternatively if the goal was to chain these migrators, we could do that as well (for [example]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/10d319a217caeb092a09138b27d19505823676d3/recipe/migrations/cuda_112_ppc64le_aarch64.yaml#L15-L16 )). AFAICT that is not being done in this or other versioned migrator cases. Maybe I'm missing something though

**Comment by beckermr** [comment]
We just let the bot do its thing usually.

**Comment by jakirkham** [comment]
How does it choose which of these migrators to apply then?

**Comment by beckermr** [comment]
They are separate in the code base. It runs them as two things and will make two PRs.

**Comment by jakirkham** [comment]
What happens if both PRs are merged? Does the feedstock then build for both versions? Or does it end up picking one (like the latest version)?

**Comment by beckermr** [comment]
It will end up doing whatever version is merged last.

**Comment by beckermr** [comment]
Once all of the migrations are closed and the feedstock is rebuilt for some other reason, it will move to the latest version.

**Comment by h-vetinari** [comment]
There are now 4 open poppler migrations (added 23.04 & 23.05)

**Comment by h-vetinari** [comment]
Closed by #4744
