### ISSUE TITLE
Drop Python 3.8

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#5013]
Recently we added the Python 3.12 migration ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4914 ). Typically when we have added a new Python version we have bumped the minimum Python version supported as well. Currently Python 3.8 is the minimum. So am proposing we drop Python 3.8 moving our minimum Python version to 3.9. Thoughts?

cc @conda-forge/core

**Comment by xhochy** [comment]
We had a bit of discussion on this topic in some place (maybe the private core chat?). The gist of it (and if we never find a reference, happy to take this simply as the expression of solely my opinion) was to keep Python 3.8 as part of the CI matrix as long as we don't see issues with the load.

In the end, this comes down to the decision on whether we, as conda-forge, want to follow CPython's schedule for support or NumPy's NEP29 which is a bit stricter in dropping old versions.

**Comment by h-vetinari** [comment]
This was discussed in one of the recent core calls, and should be in the minutes. While we're free to adapt our choice as necessary, there was a clear desire to match CPython's support window, as long as it doesn't blow out our resources.

**Comment by jakirkham** [comment]
Well offline the other day there was also a discussion about the CI queue getting larger. So think it is worth raising what resources we want to commit to this

Put another way every decision where we commit resources to one item means another item may not get them. Not to say it is exactly zero sum (we can ask for more resources from those who make asks of us), but there is some trade off that we need to be considering and the impact it has on what we are able to do

**Comment by h-vetinari** [comment]
Yes, we're all aware of the resource constraints, but not nearly all of the growth in our consumption is due to another python version (e.g. we dropped pypy3.8, so the full matrix is still 6 builds); there's also an overall growth of conda-forge in terms of package, and some stacks just have 2-3+h builds across multiple feedstocks, so if those get touched by a migration it's a big hit. 

@jezdez mentioned that we should be able to get the pool from azure pipelines to be increased, which would obviate that discussion, but in any case, dropping 3.8 was considered having a broad impact on the wider ecosystem, so we decided to try to keep supporting it (with a caveat that it's best effort and we can change our minds of course), and see how things develop.

**Comment by h-vetinari** [comment]
I updated https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790 to build against 2.0.0rc1 directly; it looks like it still needs a smithy fix, see https://github.com/conda-forge/conda-smithy/issues/1911

**Comment by hmaarrfk** [comment]
> In the end, this comes down to the decision on whether we, as conda-forge, want to follow CPython's schedule for support or NumPy's NEP29 which is a bit stricter in dropping old versions.

One way that I'm reconciling with this is:

1. CPython's schedule is for the builds should be followed for the builds of the "CPython" package itself. It shouldn't add burden to other downstream maintainers. CPython may choose to release security patches when it finds it necessary to do so. The maintainers of the python package at conda-forge should be able to make the best decision there.
2. NEP29 (or [SPEC0](https://scientific-python.org/specs/spec-0000/)) is specifically about how maintainers should feel about building *new* packages against *old* python versions. As such, it would encourage dropping python 3.8 from the build matrix.

One way to reconcile this is to:
1. Drop python 3.8 from the default build matrix. Note that users of Python 3.8 will be able to continue to use any packages that are currently built against Python 3.8.
2. Write a "python migrator" but "freeze it immediately".
3. Those that wish to still build against 3.8 would be able to pull in the migrator file to their feedstock, and build for python 3.8 as an "opt in".

**Comment by xhochy** [comment]
I feel like the hurdles we experience in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790 support dropping Python 3.8. 

Personally, I feel like we would help ourselves a lot by adopting a certain policy here. This would make it easier for all consumers what is expected to be supported. Given that a fair share of people involved are interested in scientific Python packages, I have the preference to adopt SPEC0.

**Comment by isuruf** [comment]
I don't think we should adopt SPEC0 as conda-forge has grown out of a being a scientific python community to a general python community. Dropping a python version because of a need to release an ABI breaking downstream package (albeit a very important package) as a pre-release seems like the wrong thing to do. We should have this discussion after numpy 2.0 is released to not have that over our heads so that we decide on what's best for the community.

**Comment by hmaarrfk** [comment]
> I don't think we should adopt SPEC0 as conda-forge has grown out of a being a scientific python community to a general python community.

Whether it is SPEC0 or not I would prefer to move to a strict "time bound" policy for dropping versions.

Its very "tiring" to have these discussions about backward compatibility. The reason I support NEP29/SPEC0 is that somebody took the time to address the concerns, and draw a line somewhere. (FWIW, I'm asking Numpy to adhere to their own suggestions and drop python 3.9 https://mail.python.org/archives/list/numpy-discussion@python.org/thread/AHTATJKGUEOILBNUI5IGGZPXJ5FXIRAU/ )

> Dropping a python version because of a need to release an ABI breaking downstream package (albeit a very important package) as a pre-release seems like the wrong thing to do.

Preparing for Numpy 2.0 has been chosen by many of the core developers as a project that is of importance to the community.
We must weigh the maintenance time of the "3.8" ecosystem, to that of the "future numpy ecosystem".

I don't think there is ever "a right time" to have these dicussions, the pending numpy 2.0 release is just a good forcing function for this discussion.

**Comment by hmaarrfk** [comment]
Is there really still appetite to build *new* packages for python 3.8 or 3.9?

My feeling is that:

1. Continue to release patch release of python 3.8 and 3.9 as they come in.
2. Stop rerendering recipes as python 3.8.
4. Encourage maintainers to write `python >=3.10` in their noarch packages.

This way we:

1. Continue to release security releases for python 3.8, 3.9 for as long as python supports it.
2. Continue to allow people to use python 3.8 or 3.9 should they want to in new environments with the same old packages they always had.
3. Free up our own time and mental space.

Again, we wouldn't stop buliding new patch versions of the python package itself, just stop reduce our downstream matrix to:

* Today: `3.10, 3.11, 3.12`
* And in accordance with spec0, `3.11, 3.12, 3.13` later in the year.

"3 versions" of python seems plenty for me.

**Comment by isuruf** [comment]
Yes, let's keep building downstreams for 3.9. As long as python 3.9 is supported, some packages will keep supporting 3.9 and conda-forge packages are used in their CI configurations and having new packages is important for development.

**Comment by dopplershift** [comment]
> Encourage maintainers to write python >=3.10 in their noarch packages.

Strong -1 on this. Make the recipe reflect the metadata that's encoded by upstream. I can see an argument for the unclear "Python>3", but otherwise we're just breaking configurations that would otherwise work and create confusion against configurations that upstream intends to support.

**Comment by h-vetinari** [comment]
> > Encourage maintainers to write python >=3.10 in their noarch packages.
> 
> Strong -1 on this. Make the recipe reflect the metadata that's encoded by upstream. I can see an argument for the unclear "Python>3", but otherwise we're just breaking configurations that would otherwise work and create confusion against configurations that upstream intends to support.

The flipside of this is that we have a lot of `python >=3.6` and 3.7 lower bounds in noarch recipes, which are broken already in many cases because upstream started using newer python features and the feedstocks never change the bound because CI remains green.

I think it would make sense to set the lower bound in noarch recipes to our oldest supported python version. That's realistically the only thing we can test and support. Upstream may support more, but conda-forge doesn't have to - when we drop python 3.8, that IMO should include noarch packages.

Perhaps not as an obligation, but at least as a linting rule. 

> Figure at this point we would drop it whenever we add Python 3.13, which is likely not far away either

👍 That's the plan AFAIU it

**Comment by jakirkham** [comment]
> The flipside of this is that we have a lot of `python >=3.6` and 3.7 lower bounds in noarch recipes, which are broken already in many cases because upstream started using newer python features and the feedstocks never change the bound because CI remains green.
> 
> I think it would make sense to set the lower bound in noarch recipes to our oldest supported python version. That's realistically the only thing we can test and support. Upstream may support more, but conda-forge doesn't have to - when we drop python 3.8, that IMO should include noarch packages.
> 
> Perhaps not as an obligation, but at least as a linting rule.

Could we please move this discussion to issue ( https://github.com/conda-forge/conda-forge.github.io/issues/2210 )?

Think this is a good conversation to have and there's already some thoughts in that issue

**Comment by h-vetinari** [comment]
> @jezdez mentioned that we should be able to get the pool from azure pipelines to be increased, which would obviate that discussion, [...]

Reading this old thread again, I wonder if we can prioritize the interaction with MSFT / Azure Pipeline again. Conda-forge has grown a lot, but our limit of 200(?) agents hasn't changed in a long time.

**Comment by isuruf** [comment]
Opened a PR to drop in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6344

**Comment by hmaarrfk** [comment]
Did i miss a conversation? I thought we were on track to keeping support until Oct 2024.

**Comment by h-vetinari** [comment]
I agree with Isuru here. My understanding of the discussion w.r.t. PEP 602 (one example from the core call minutes is [here](https://github.com/conda-forge/conda-forge.github.io/blob/6267a800dfaaf6d818e641e591103a663bf0f5a8/community/minutes/2023-09-20.md?plain=1#L49-L53)) was that we'd do a best effort to keep building 3.8 towards its EOL, even if that means one more entry in the CI matrix everywhere.

But we've ~always used new python migrations as a reason to get rid of a version that's (close to) EOL, and I think we shouldn't change that, because it makes sense on a lot of levels (c.f. Isuru's comment above). Let's keep the CI matrix from blowing up, the migration will be enough work as-is IMO.

**Comment by hmaarrfk** [comment]
I understand if we want to say "until the appropriate RC is released"

**Comment by isuruf** [comment]
That's a good idea. We can say

python 3.X is supported until EOL or until python 3.(X+5).rc1 is released whichever comes first.

**Comment by jaimergp** [comment]
> python 3.X is supported until EOL or until python 3.(X+5).rc1 is released whichever comes first.

Should we encode this as a CFEP?

**Comment by jakirkham** [comment]
We could. Though I think it is important to remember that this is a volunteer effort with donated resources. IOW we should not tie ourselves to an anchor that makes it hard for us to adapt to changing constraints

**Comment by jaimergp** [comment]
At the very least document it so we have a reference we can use next time this conversation comes up.

**Comment by jakirkham** [comment]
Yes this is why I was suggesting we open a dedicated issue on this topic to discuss as opposed to having it in the annual Python bringup/drop issues & PRs

Simply having the conversation in one easy to find place would be quite helpful for our future selves

**Comment by jaimergp** [comment]
I finally added an issue in python-feedstock to keep it findable: https://github.com/conda-forge/python-feedstock/issues/794
