### ISSUE TITLE
3 simultaneous poppler migrations

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#5717]
### Comment:

It seems like there are 3 active migrations

* https://conda-forge.org/status/migration/poppler2312
* https://conda-forge.org/status/migration/poppler2402
* https://conda-forge.org/status/migration/poppler2403

Can we close the 2 older ones?

@conda-forge/poppler would there be a more sustainable way to avoid multiple simultaneous migrations? This seems to be a trend

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4271
xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4270

**Comment by pkgw** [comment]
Yeah, this happens pretty regularly. In my view, the main issue is that there are a few packages that depend on poppler that are very lightly maintained, so the migrations generally stall on them just because no one's looking at the PRs. If we gave those packages explicit poppler pins in their `meta.yaml` files, would that exempt them from the migrator? I think that that would help the migrations finish, even if they're coming every month or so with the new Poppler releases and our strict pinning.

**Comment by hmaarrfk** [comment]
I'm happy to be more aggressive about closing them "early". I feel like without building two versions of a package, migrators should be closed soon after the leaf package PRs are made. 

It makes little sense to keep them open for too long.

**Comment by jakirkham** [comment]
Yes this is why the progress bar on the status page measures percent complete using all migration PRs made (whether or not they have been merged)
