### ISSUE TITLE
R package feedstocks appear unnecessarily blocked from migration PRs

### ISSUE THREAD

**Issue by mfansler** [conda-forge/conda-forge-pinning-feedstock#6401]
With https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6381, many R package feedstocks now appear blocked from getting migrations because they now regard some `xorg-*` packages as parents. It should be noted that these are not explicit dependencies that are blocking.

Concrete example: `r-magick` is listed as depending on `xorg-libx11`, `xorg-libxt`, `xorg-libxext`, `xorg-libxrender`, but none of these are explicitly declared.

Because none of these new "parents" fall under the purview of the Conda Forge R team, this is unfortunately out of our hands. Any way we can see this resolved?

CC: @isuruf @zklaus

**Comment by mfansler** [comment]
CC: @conda-forge/r

**Comment by isuruf** [comment]
There was a bug in the migrator that didn't consider these packages for the m2w64-ucrt migration which was fixed recently in #6381. On Linux, `r-base` depends on these xorg-* packages and that's why the R packages are marked as dependencies. These packages should be built soon and the R migration will go forward.
