### ISSUE TITLE
reenable `DEFAULT_LINUX_VERSION` for cos7, alma8, alma9, etc.

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-pinning-feedstock#6629]
This option was removed when we dropped cos6.

Per the discussion on the core call, we are going to reenable this option since the CUDA zip in the pinnings makes it hard to do this in the cbc.yaml directly.

cc @h-vetinari @isuruf

**Comment by jakirkham** [comment]
Have implemented this for `cos7` and `alma8` in PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6548

It would be simple to extend to `alma9` when we are ready

**Comment by h-vetinari** [comment]
I also updated my PR to do this (including the alma9 images and removing `cdt_name` from the zip). However, I wanted to note a pertinent comment in the discussion in #6548 that we could simply always use the newest available image by default. This should obsolete the necessity for `DEFAULT_LINUX_VERSION` completely, because the only point where we really need that is if we need a newer image for some reason.

This comment is mostly for cross-referencing purposes, I think the discussion fits better in https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/6283, which is where I put my [thoughts](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/6283#issuecomment-2452891617) on this.
