### ISSUE TITLE
Packages have grpc-cpp migrated to 1.32 but conda-forge pinning is still 1.30

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/conda-forge-pinning-feedstock#800]
It looks like there's a `grpc-cpp` migration happening now to move to 1.32, but it's blocked by https://github.com/conda-forge/arrow-cpp-feedstock/pull/170 which seems a bit non-trivial to resolve.

Other packages like `google-cloud-cpp` have migrated to `grpc-cpp` 1.32 and have subsequently released a new version which only built on `grpc-cpp` 1.32.

This leads to packages depending on `google-cloud-cpp` being in a possibly broken state if their `host` requirements and `run` requirements differ. For example, if a library has `google-cloud-cpp` in `host` and `pyarrow` in `run`, it becomes an unsolvable situation due to the `grpc-cpp` versioning difference.

**Comment by scopatz** [comment]
CC @CJ-Wright @isuruf

**Comment by isuruf** [comment]
It's better to fix arrow-cpp. Looks trivial to me to patch orc.

**Comment by jakirkham** [comment]
Based on those closer to this work, it does not sound trivial to patch ( https://github.com/dask/dask/issues/6615 ). That said, it sounds like dropping `orc` may unblock this work. Asking some folks internally to see how that may impact us.

cc @xhochy

**Comment by isuruf** [comment]
How is it not trivial? There's already a PR by @nehaljwani in https://github.com/apache/orc/pull/541

**Comment by jakirkham** [comment]
Will defer to others more closely associated with that work to comment.

**Comment by xhochy** [comment]
The more we come into this situations, the more I prefer to rebuild with old and new as we did with boost **in general**. It costs more CI resources but less human effort (which is the more limited resource).

**Comment by isuruf** [comment]
If we build with both, the migrator will still be blocked at some point. It's not going to change anything

**Comment by xhochy** [comment]
The migrator won't move faster but it would solve @kkraus14 initial problem.

**Comment by CJ-Wright** [comment]
To your point @xhochy 
xref: https://github.com/conda-forge/cfep/pull/32

CC: @beckermr

**Comment by isuruf** [comment]
migrators not moving faster is a problem as this would result in a combinatorial explosion and will quickly make the CI slower.
Besides, it's not the migrator that is at fault here. It's a package vendoring a static library.

There's also the reverse problem that some packages only support the newer upstream version in newer versions and those downstream packages will need to maintain two branches.

IMO, the current status quo is the least amount of work

**Comment by beckermr** [comment]
I am going to write a summary here in an effort to help clarify things for my own sake.

There are three general options. 

1. Do a standard migration where we move to the new pin and replace the old one.
2. Do what we did with boost where we add the new pin, keeping the old one.
3. Do what was proposed in conda-forge/cfep#32. In that case, the bot would create a new branch on the feedstock that builds the old pin while the migration is going. The new pin is built on master. Then the old pin branch would be removed once the migration is done. 

Option 2 solves the issue raised here (a version not available) but still leaves some things blocked since the builds of both versions are in the same CI run and bot PR. It is sensible for long-running migrations or subgraphs where there are dense dependencies between packages with tight constraints.

Option 3 solves the issue raised here and has the potential to unblock things since each branch could be built independently either the new or old pin. It is certainly the most general but is definitely more work than 1 or 2.

The debate here is about permissions (should the bot have rights to make branches?) and workload (Which option is the least amount of work? Who does the work?).

**Comment by jakirkham** [comment]
Maybe a good topic for our next meeting? 😉

**Comment by beckermr** [comment]
We've debated it before and not gotten to consensus. I don't see what is qualitatively different this time. However, I am happy to discuss this more as always!

**Comment by xhochy** [comment]
Closing this as the migration has finished.
